files:
  - source: /common/src/main/resources/bending/lang/messages_en.properties
    translation: /common/src/main/resources/bending/lang/messages%two_letters_code%.properties
commit_message: '[ci-skip]'
