blank_issues_enabled: true
contact_links:
  - name: Bending Discord Server
    url: https://discord.gg/sjwncgE
    about: If you have any questions or need help, don't hesitate to ask.
  - name: Bending Matrix Room
    url: https://matrix.to/#/#bending:matrix.org
    about: Bridged Matrix room.
