name: Feature Request
description: Suggest an idea for Bending
labels: [ "enhancement" ]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Please give some context for this request. Why do you want it added?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you are proposing.
      description: A clear and concise description of what you want.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered.
      description: List any alternatives you might have tried.
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Other
      description: Add any other context or screenshots about the feature request below.
    validations:
      required: false
