name: Bending
version: ${pluginVersion}
main: me.moros.bending.Bending
author: Moros
description: Bending plugin for PaperMC.
website: https://github.com/PrimordialMoros/Bending
softdepend: [PlaceholderAPI, WorldGuard, GriefPrevention, Towny, LWC, LuckPerms]
api-version: 1.19
