name: Bending
version: '${pluginVersion}'
loader: me.moros.bending.paper.BendingLoader
main: me.moros.bending.paper.BendingBootstrap
author: Moros
description: Bending plugin for PaperMC.
website: https://github.com/PrimordialMoros/Bending
api-version: '1.20'
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    GriefPrevention:
      load: BEFORE
      required: false
    LWC:
      load: BEFORE
      required: false
    Towny:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false
